**NumPy的ndarray**
- n维的数组对象
- 数组中所有元素的类型必须相同

**创建方式**
- np.array() 
 - 将输入的列表、元组、数组等序列类型转换我ndaray对象
- np.asarray() 
 - array()和asarray()都可以将结构数据转化为ndarray，但是主要区别就是当数据源是ndarray时，array仍然会copy出一个副本，占用新的内存，但asarray不会
- np.zeros() 
 - 根据指定形状创建一个全为0的ndarray对象
- np.zeros_like() 
 - 传入一个数组作为参数，根据该数组的形状和dtype创建一个全0的ndaray对象
- np.ones() 
 - 根据指定形状创建一个全为1的ndarray对象
- np.ones_like() 
 - 传入一个数组作为参数，根据该数组的形状和dtype创建一个全1的ndaray对象
- np.empty()
 - 根据指定形状创建ndarray对象，只分配内存但是不填充任何值
- np.empty_like() 
 - 同上
- np.full() 
 - 根据指定形状传建一个ndarray对象，并用fill_value的值进行填充           
- np.full_like()  
 - 传入一个数组作为参数，根据该数组的形状创建一个ndarray对象，并用fill_value的值进行填充
- np.eye() 
 - 传入一个整数N，创建一个N * N的单位矩阵   
- np.identity() 
 - 传入一个整数N，创建一个N * N的单位矩阵
- np.random 
 - 随机抽样创建
- np.arange() 
 - 在给定间隔内返回均匀间隔的值（一位数组）
- np.linspace() 
 - 返回指定间隔内的等距数字。
- np.fromfunction()
 - 通过对每个坐标执行函数来构造数组
- np.fromfile()
 - 从文本或二进制文件中的数据构造数组

In [1]:
import numpy as np

# data1也可以是tuple类型
# data1可以进行嵌套
data = [[1,2,3], [4,5,6]]
arr1 = np.array(data)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
arr2 = np.asarray(arr1)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr3 = np.zeros([3, 4])
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
arr4 = np.zeros_like(data)
arr4

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
arr5 = np.ones([2, 3])
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr6 = np.ones_like(data)
arr6

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
# 可以直接在终端中演示
arr7 = np.empty([2, 2]) 
arr7

array([[2.18060794e-314, 2.18037569e-314],
       [2.18060792e-314, 2.18045592e-314]])

In [8]:
arr8 = np.empty_like(data)
arr8

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [9]:
arr9 = np.full([2,3], fill_value=3)
arr9

array([[3, 3, 3],
       [3, 3, 3]])

In [10]:
arr10 = np.full_like(data, 8)
arr10

array([[8, 8, 8],
       [8, 8, 8]])

In [11]:
# numpy.identity(n, dtype=None)
arr11 = np.identity(5)
arr11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
"""
numpy.eye(N, M=None, k=0, dtype=<class‘float’>, order=’C’)
N: 行数
M：列数，默认等于N
k：对角线索引：0（默认）为主对角线，正值是指上对角线，负值是指到下对角线
order: {'C', 'F'}输出是否应存储在主要行（C样式）中或内存中的列主（Fortran样式）顺序
"""
arr12 = np.eye(5)
arr12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr13 = np.random.randn(2, 3)
arr13

array([[-1.1381773 ,  1.32714134, -0.05908729],
       [-1.2037372 , -0.95742676,  1.2633915 ]])

In [14]:
"""
参数
start：开始位置，数字，可选，默认值为0
stop：结束位置，数字，
step：步长，数字，可选，默认为1。如果指定step则必须指定start
dtype：类型。不指定则自动推断
"""
arr14 = np.arange(start=0, stop=10, step=2)
arr14

array([0, 2, 4, 6, 8])

In [15]:
arr15 = np.linspace(0, 10, 5)
arr15

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
def fun(x, y):
    return x * 10 + y

np.fromfunction(fun, (4, 5), dtype=np.int)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [17]:
np.fromfunction(lambda i :i ,(4,))

array([0., 1., 2., 3.])

In [18]:
np.fromfunction(lambda i,j:i+j,(2, 3))

array([[0., 1., 2.],
       [1., 2., 3.]])

In [19]:
np.fromfunction(lambda i,j:i+j,(2, 3)）

SyntaxError: invalid character in identifier (<ipython-input-19-12c860256290>, line 1)

> np.fromfile(file, dtype=float, count=-1, sep='')
- file：要打开的文件对象或者文件名
- dtype：返回数组的数据类型。对于二进制文件，它用于确定文件中项目的大小和字节顺序。错误的数据类型会返回错误的数据
- count：要读取的项目数。-1表示所有项目（即完整文件）
- sep：如果文件是文本文件，则表示分隔项之间的分隔符。空（“”）分隔符表示应将文件视为二进制文件。分隔符中的空格（“”）与零个或多个空白字符匹配。仅由空格组成的分隔符必须至少与一个空格匹配

In [ ]:
np.fromfile('./file/fromfile')

In [ ]:
np.arange(12).tofile('./file/intfile')

In [ ]:
np.fromfile('./file/intfile') # 默认的dtype是float