**NumPy的数据类型**
- ndarray对象的dtype属性中描述了该对象的数据类型信息，返回一个dtype对象
- 调用astype()会创建一个新对象，不会改变原对象
- 所有的数据类型如下表所示：

<table border="1" style="text-align:left;">
<tr><th>类型</th><th>类型代码</th><th style="width:50%; ">说明</th></tr>
<tr><td>int8、uint8</td><td>i1、u1</td><td>有符号和无符号的8位（1个字节）整形</td></tr>
<tr><td>int16、uint16</td><td>i2、u2</td><td>有符号和无符号的16位（2个字节）整形</td></tr>
<tr><td>int32、uint32</td><td>i4、u4</td><td>有符号和无符号的32位（4个字节）整形</td></tr>
<tr><td>int64、uint64</td><td>i8、u8</td><td>有符号和无符号的64位（8个字节）整形</td></tr>
<tr><td>float16</td><td>f2</td><td>半精度浮点数</td></tr>
<tr><td>float32</td><td>f4或f</td><td>标准的单精度浮点数</td></tr>
<tr><td>float64</td><td>f8或d</td><td>标准的双精度浮点数</td></tr>
<tr><td>float128</td><td>f16或g</td><td>扩展精度浮点数</td></tr>
<tr><td>complex64、complex128、complex256</td><td>c8、c16、c32</td><td>分别用两个32位、64位或128位浮点数表示的复数</td></tr>
<tr><td>bool</td><td>?</td><td>存储布尔类型</td></tr>
<tr><td>object</td><td>O</td><td>Python对象类型</td></tr>
<tr><td>string_</td><td>S</td><td>固定长度的字符串类型（每个字符1个字节）</td></tr>
<tr><td>unicode_</td><td>U</td><td>固定长度的unicode类型（字节数由平台决定）</td></tr>
</table>

In [2]:
import numpy as np

int_arr = np.arange(9).reshape(3, 3)
int_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**可以通过dtype属性获得类型信息**

In [3]:
int_arr.dtype

dtype('int32')

**创建指定numpy类型的标量**

In [4]:
var_float16 = np.float16([12, 121])
var_float16

array([ 12., 121.], dtype=float16)

In [5]:
var_float16.dtype

dtype('float16')

**可以通过astype()方法转换数据类型**

In [21]:
float_arr = int_arr.astype(np.float32) # 'f'等效于np.float32
float_arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [22]:
# 如果将浮点数转换成整数，小数部分会被直接删除
float_arr2 = np.array([1.2, 2.6, 3.5, 4.9, 5.0])
float_arr2

array([1.2, 2.6, 3.5, 4.9, 5. ])

In [23]:
float_arr2.astype('int')

array([1, 2, 3, 4, 5])

In [25]:
# 字符串也可以转为数字类型
str_arr = np.array(['1.23', '2.36', '100', '-236.123', '00'], dtype=np.string_)
str_arr

array([b'1.23', b'2.36', b'100', b'-236.123', b'00'], dtype='|S8')

In [26]:
str_arr.astype('float')

array([   1.23 ,    2.36 ,  100.   , -236.123,    0.   ])

**调用dtype的mro方法即可查看其所有的父类**

In [14]:
np.int32.mro()

[numpy.int32,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

**可以使用issubdtype()判断类型**

In [10]:
np.issubdtype(float_arr.dtype, np.floating)

True

In [3]:
np.issubdtype(np.int32, np.floating)

False