### **NumPy数组计算**
- 不同类型的数组计算之后的结果的类型会向上转换为更精确的类型（如int类型的数组a和float类型的数组b求和得到c的类型为float，而不是int）


In [1]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### 1、数组与标量的算术运算会将标量传播到各个元素

- 数组与标量的算术运算可以看做最简单的广播

In [2]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [3]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

### 2、shape相同的数组之间的算术运算在相同位置的元素上进行
- *=、+=运算会修改原对象，而不是创建新对象

In [4]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr *= 2
arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

- shape相同的数组之间比较会生成布尔数组

In [10]:
arr + 1 > arr

array([[ True,  True,  True],
       [ True,  True,  True]])

### 3、矢量化
- 用数组表达式替换显式for循环