### **拷贝**

NumPy中拷贝分为三种情况：
- 完全不拷贝
> 一个数组的任何变化都反映在另一个数组上，包括值变化和形状变化

- 浅拷贝
> 一个数组值会变化会反映在另一个数组上，但是形状不变化

- 深拷贝
> 创建原数组的副本，副本的任何变化都不会反映在原数组上

In [15]:
import numpy as np

In [35]:
# 完全不拷贝
a = np.arange(12)
b = a
a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
b[5] = 500
a
b

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9,  10,  11])

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9,  10,  11])

In [37]:
b is a

True

In [38]:
b.shape = (2, 6)
a
b

array([[  0,   1,   2,   3,   4, 500],
       [  6,   7,   8,   9,  10,  11]])

array([[  0,   1,   2,   3,   4, 500],
       [  6,   7,   8,   9,  10,  11]])

In [39]:
# 浅拷贝
a = np.arange(12)
c = a.view()
a
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
c is a

False

In [41]:
c.base is a

True

In [42]:
c[2] = 200
a
c

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [43]:
c.shape = (12, 1)
a
c

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([[  0],
       [  1],
       [200],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11]])

In [44]:
# 深拷贝
a = np.arange(12)
d = a.copy()
a
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
d is a

False

In [47]:
a[1] = 100
a
d

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
d.shape = (12, 1)
a
d

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])