## 1、重塑(reshape)

- 重塑的各个维度上整数的乘积必须等于arr.size

In [2]:
import numpy as np

arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr.reshape(4, 3) # order默认为‘C’

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
arr.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### 多维数组重塑

In [8]:
ndarr = arr.reshape(4, 3, order='F')
ndarr

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
ndarr.reshape(2, 6)

array([[ 0,  4,  8,  1,  5,  9],
       [ 2,  6, 10,  3,  7, 11]])

In [8]:
# 重塑为三维度
arr.reshape((2,2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## 2、扁平化处理

In [10]:
ndarr

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [13]:
ndarr.flatten()

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [14]:
ndarr.ravel()

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

## 3、数组合并

<table border="1" style="text-align:left;">
        <tr><th>函数</th><th style="width:50%; ">说明</th></tr>
        <tr><td>concatenate</td><td>沿着一条轴连接一组数组</td></tr>
        <tr><td>vstack、row_stack</td><td>以追加行的方式对数组进行连接（沿轴0）</td></tr>
        <tr><td>hstack</td><td>以追加列的方式对数组进行连接（沿轴1）</td></tr>
        <tr><td>column_stack</td><td>类似于hstack，但是会先将一维数组转换为二维列向量</td></tr>
        <tr><td>dstack</td><td>以面向“深度”的方式对数组进行叠加</td></tr>
    </table>

## 4、数组拆分

<table border="1" style="text-align:left;">
        <tr><th>函数</th><th style="width:50%; ">说明</th></tr>
        <tr><td>split</td><td>沿指定轴在指定的位置拆分数组</td></tr>
        <tr><td>hsplit、vsplit、dsplit</td><td>split的便捷化函数，分别沿轴0、轴1、轴2进行拆分</td></tr>
    </table>

## 5、repeat和tile

### 5.1 repeat

In [16]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [17]:
arr.repeat(2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [19]:
# 指定每个元素的重复次数
# 0重复2次，1重复3次，2重复4次，3重复5次
arr.repeat([2, 3, 4, 5])

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3])

#### 多维数组repeat

In [20]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
arr.repeat(2) # 不指定轴会被扁平化

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [30]:
arr.repeat(2, axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

In [31]:
arr.repeat(2, axis=1)

array([[0, 0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5, 5]])

### 5.2 tile

In [33]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
np.tile(arr, 2) # 对标量是横向扩展

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [42]:
np.tile(arr, (1,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [43]:
np.tile(arr, (2,1))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

### 6、数组转置和轴对换

- 转置和轴对换返回的是原对象的视图，不是新对象

In [44]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
arr.T[:2] = 0
arr

array([[ 0,  0,  2,  3],
       [ 0,  0,  6,  7],
       [ 0,  0, 10, 11]])