### **索引和切片**
- 数组切片是原始数组的视图，不是复制品，如果要得到切片的副本，应该使用copy()方法
- 在多维数组中索引，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）

#### **1、切片**
> 切片的基本语法 ndarray[i : j : k]，其中i为起始下标，j为结束下标（不包括j），k为步长（默认为1）

In [1]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr[1:9:2]

array([1, 3, 5, 7])

In [3]:
arr[4:-3]

array([4, 5, 6])

In [4]:
arr[9:4:-2]

array([9, 7, 5])

In [5]:
a = arr[::2]
a

array([0, 2, 4, 6, 8])

In [6]:
arr[:6] = 0

In [7]:
arr[6:]

array([6, 7, 8, 9])

In [8]:
arr[:] = 1
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

多维切片

In [9]:
ndarr = np.arange(16).reshape((4, 4))
ndarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
ndarr[:2] # 行，等效于arr2[:2, :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
ndarr[:2, :2] # 前两行的前两列

array([[0, 1],
       [4, 5]])

In [12]:
ndarr[::2, -2] # 步长为2的行的倒数第二列

array([ 2, 10])

#### **2、索引**

In [13]:
arr = np.arange(10)
ndarr = np.arange(16).reshape((4, 4))
arr
ndarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
arr[1]

1

In [15]:
ndarr[1,1]

5

In [16]:
ndarr[1, 1] # 等效于ndarr[1][1]，但是后者速度更慢

5

In [17]:
ndarr[2, [1, 2]] # 第2行的第1、2列元素

array([ 9, 10])

In [18]:
ndarr[:3, [0,1]] # 前3行的第0、1列元素

array([[0, 1],
       [4, 5],
       [8, 9]])

**布尔索引**

In [19]:
cities = np.array(['bj', 'cd', 'sh', 'gz', 'cd'])
cities

array(['bj', 'cd', 'sh', 'gz', 'cd'], dtype='<U2')

In [20]:
data = np.arange(20).reshape(5, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
cities == 'cd'

array([False,  True, False, False,  True])

In [22]:
data[cities == 'cd']

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [23]:
data[cities == 'cd', :1]

array([[ 4],
       [16]])

In [24]:
# data[:, cities=='cd'] # 注意：如果布尔型数组的长度不对，布尔型选择就会出错

还可以这样？

In [25]:
cities != 'cd'

array([ True, False,  True,  True, False])

In [26]:
data[cities != 'cd']  # 等效于 data[~(cities == 'cd')] 

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
data[cities != 'cd', :1] # 等效于 data[~(cities == 'cd'), :1]

array([[ 0],
       [ 8],
       [12]])

**花式索引** —— 指的是利用整数数组进行索引

In [28]:
arr3 = np.arange(36).reshape(6,6) 
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [29]:
# 取出第3，2, 5行
arr3[[3, 4, 5]]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [30]:
# 使用负数索引将会从末尾开始选取行
arr3[[-4, -2 , -1]]

array([[12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [31]:
arr3[[1, 2, 3], [1, 2, 3]] # 取出下标为(1, 1), (2, 2), (3, 3)的元素 

array([ 7, 14, 21])

In [32]:
arr3[[1, 2, 3]][:, [1, 2, 3]]  # 同时在行和列上进行花式索引

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])