**排序**
- sort()
    - arr.sort()会直接修改arr本身
    - np.sort()返回一个排序后的副本，不修改原数组

    参数说明:
    > sort(axis=-1, kind='quicksort', order=None)
    > 
    > axis：排序沿数组的（轴）方向，0表示按行，1表示按列，None表示展开来排序，默认值为-1，表示沿最后的轴排序
    >
    > kind：排序的算法，提供了快排'quicksort'、混排'mergesort'、堆排'heapsort'， 默认为‘quicksort'
    >
    > order：排序的字段名，可指定字段排序，默认为None

- lexsort(keys[, axis])	使用一系列键执行间接排序。
- argsort(a[, axis, kind, order])	返回对数组进行排序的索引。
- ndarray.sort([axis, kind, order])	就地对数组进行排序。
- msort(a)	返回沿第一个轴排序的数组副本。
- sort_complex(a)	首先使用实部对复杂数组进行排序，然后使用虚部进行排序。
- partition(a, kth[, axis, kind, order])	返回数组的分区副本。
- argpartition(a, kth[, axis, kind, order])	使用kind关键字指定的算法沿给定轴执行间接分区。


In [3]:
import numpy as np

arr1 = np.random.randn(10)
arr1

array([ 0.04245784,  0.78293867, -0.24102925, -0.53719802, -0.23311417,
        0.55442962, -0.71754646,  0.475932  ,  0.84569377,  0.91639913])

In [4]:
np.sort(arr1)

array([-0.71754646, -0.53719802, -0.24102925, -0.23311417,  0.04245784,
        0.475932  ,  0.55442962,  0.78293867,  0.84569377,  0.91639913])

In [5]:
arr1.sort()
arr1

array([-0.71754646, -0.53719802, -0.24102925, -0.23311417,  0.04245784,
        0.475932  ,  0.55442962,  0.78293867,  0.84569377,  0.91639913])

多维数组排序

In [6]:
arr2 = np.random.randn(3, 4)
arr2

array([[-2.0231105 ,  0.45299572, -1.24832653,  0.31121567],
       [ 1.08354443,  0.84434128, -0.54484272, -1.36247832],
       [-0.68414069,  0.60621733, -1.26834171, -0.57610449]])

In [7]:
np.sort(arr2, axis=1) # 按列排序

array([[-2.0231105 , -1.24832653,  0.31121567,  0.45299572],
       [-1.36247832, -0.54484272,  0.84434128,  1.08354443],
       [-1.26834171, -0.68414069, -0.57610449,  0.60621733]])

In [8]:
np.sort(arr2, axis=0) # 按行排序

array([[-2.0231105 ,  0.45299572, -1.26834171, -1.36247832],
       [-0.68414069,  0.60621733, -1.24832653, -0.57610449],
       [ 1.08354443,  0.84434128, -0.54484272,  0.31121567]])

In [9]:
my_dt = np.dtype([('name',  'S10'),('age',  int)])
my_dt

dtype([('name', 'S10'), ('age', '<i4')])

In [10]:
arr3 = np.array([("Mike",21),("Nancy",25),("Bob",  17),  ("Jane",27)], dtype=my_dt)
arr3

array([(b'Mike', 21), (b'Nancy', 25), (b'Bob', 17), (b'Jane', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [11]:
np.sort(arr3, order='age')

array([(b'Bob', 17), (b'Mike', 21), (b'Nancy', 25), (b'Jane', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])