**排序**
- sort(a[, axis, kind, order]) 
> 返回数组的排序副本

- ndarray.sort([axis, kind, order]) 
> 就地对数组进行排序

- lexsort(keys[, axis]) 
> 使用一系列键执行间接排序

- argsort(a[, axis, kind, order]) 
> 返回对数组进行排序的索引

- msort(a) 
> 返回沿第一个轴排序的数组副本

- sort_complex(a) 
> 首先使用实部对复杂数组进行排序，然后使用虚部进行排序

- partition(a, kth[, axis, kind, order]) 
> 返回数组的分区副本

- argpartition(a, kth[, axis, kind, order]) 
> 使用kind关键字指定的算法沿给定轴执行间接分区

In [9]:
import numpy as np

arr1 = np.random.randn(10)
arr1

array([ 0.72425128, -1.55974414,  0.52616004, -1.46867152, -0.81885181,
       -0.72524126, -0.12968284, -0.7787037 ,  1.03384003,  0.10946823])

In [10]:
np.sort(arr1)

array([-1.55974414, -1.46867152, -0.81885181, -0.7787037 , -0.72524126,
       -0.12968284,  0.10946823,  0.52616004,  0.72425128,  1.03384003])

In [11]:
arr1.sort() # 就地进行排序，修改原数组
arr1

array([-1.55974414, -1.46867152, -0.81885181, -0.7787037 , -0.72524126,
       -0.12968284,  0.10946823,  0.52616004,  0.72425128,  1.03384003])

多维数组排序

In [15]:
arr2 = np.random.randn(3, 4)
arr2

array([[ 0.09001198,  1.08482898,  0.33006021,  0.70750344],
       [-1.30828294, -1.96147242,  1.68277292,  0.85305723],
       [ 0.5549058 , -0.22550362,  0.49554062, -0.5550557 ]])

In [16]:
np.sort(arr2, axis=1) # 按列排序

array([[ 0.09001198,  0.33006021,  0.70750344,  1.08482898],
       [-1.96147242, -1.30828294,  0.85305723,  1.68277292],
       [-0.5550557 , -0.22550362,  0.49554062,  0.5549058 ]])

In [17]:
np.sort(arr2, axis=0) # 按行排序

array([[-1.30828294, -1.96147242,  0.33006021, -0.5550557 ],
       [ 0.09001198, -0.22550362,  0.49554062,  0.70750344],
       [ 0.5549058 ,  1.08482898,  1.68277292,  0.85305723]])

In [21]:
my_dt = np.dtype([('name',  'U10'),('age',  int)]) # 按关键字排序
my_dt

dtype([('name', '<U10'), ('age', '<i4')])

按键排序

In [22]:
arr3 = np.array([("罗志祥", 21), ("黄渤", 25), ("孙红雷",  17),  ("黄磊",27)], dtype=my_dt)
arr3

array([('罗志祥', 21), ('黄渤', 25), ('孙红雷', 17), ('黄磊', 27)],
      dtype=[('name', '<U10'), ('age', '<i4')])

In [25]:
np.sort(arr3, order='age')

array([('孙红雷', 17), ('罗志祥', 21), ('黄渤', 25), ('黄磊', 27)],
      dtype=[('name', '<U10'), ('age', '<i4')])