## **数组形状变换**
- 重塑
- 扁平化处理
- 数组合并
- 数组拆分
- 数组扩充
- 数组转置和轴对换

### **1、重塑**
- ndarray.reshape(shape, order='C')
- ndarray.resize()
> reshape 函数返回修改后的新对象，而 ndarray.resize 方法修改数组本身
- 重塑的各个维度上整数的乘积必须等于arr.size
- 如果想让自动计算某个轴上的大小，可以传入-1

In [1]:
import numpy as np

arr = np.arange(12)
arr2 = arr.copy()

In [7]:
arr.reshape((4, 3)) # order默认为‘C’ ，按列读取。等效于reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
arr.reshape((4, 3), order='F') # 按行读取

# 虽然做了这么多操作  但是arr本身是没有变化的
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# resize()会修改对象本身
arr2.resize((4,3))
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

多维数组重塑

In [8]:
ndarr = arr.reshape(4, 3)
ndarr

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
ndarr.reshape(2, 6)

array([[ 0,  4,  8,  1,  5,  9],
       [ 2,  6, 10,  3,  7, 11]])

In [8]:
# 重塑为三维度
arr.reshape((2,2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
arr.reshape((3, 2, -1))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

### **2、扁平化处理**

In [25]:
ndarr = np.arange(12).reshape(3, 4)
ndarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
ndarr.flatten() # order='C'，按列

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
ndarr.flatten(order='F') # 按行

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [29]:
ravel_ndarr = ndarr.ravel() # flatten()返回新对象，ravel()返回视图
ravel_ndarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
ravel_ndarr[1] = 100
ndarr

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

### **3、数组合并**

- concatenate
> 沿着一条轴连接一组（多个）数组。除了与axis对应的轴之外，其它轴必须有相同的形状。

- vstack、row_stack
> 以追加行的方式对数组进行连接（沿轴0）

- hstack
> 以追加列的方式对数组进行连接（沿轴1）

- column_stack
> 类似于hstack，但是会先将一维数组转换为二维列向量

- dstack
> 以面向“深度”的方式对数组进行叠加

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a
b

array([[1, 2],
       [3, 4]])

array([[5, 6]])

In [41]:
np.concatenate((a, b), axis=0) # 可以查看函数说明

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
b.T

array([[5],
       [6]])

In [43]:
a.shape, b.T.shape

((2, 2), (2, 1))

In [44]:
np.concatenate((a, a.T), axis=1)

array([[1, 2, 1, 3],
       [3, 4, 2, 4]])

In [40]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])

a
b

array([[1, 2, 3],
       [4, 5, 6]])

array([[10, 20, 30],
       [40, 50, 60]])

In [43]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [45]:
np.row_stack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [46]:
np.hstack((a, b))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [47]:
np.column_stack((a, b))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [50]:
np.dstack((a, b))

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]]])

### **4、数组拆分**

- split
> 沿指定轴在指定的位置拆分数组

- hsplit、vsplit、dsplit
> split的便捷化函数，分别沿轴0、轴1、轴2进行拆分

In [20]:
split_arr = np.arange(36).reshape(6, -1)
split_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
a, b, c = np.split(split_arr, 3, axis=0) # 可以查看函数说明
a
b
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [7]:
a, b, c = np.split(split_arr, 3, axis=1) # 可以查看函数说明
a
b
c

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]])

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]])

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29],
       [34, 35]])

In [14]:
a, b, c, d = np.split(split_arr, [2, 4, 5], axis=1)
a
b
c
d

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]])

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]])

array([[ 4],
       [10],
       [16],
       [22],
       [28],
       [34]])

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

### **5、repeat和tile**

#### 5.1 repeat —— 针对元素

In [16]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [21]:
np.repeat(arr, 2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [24]:
# 指定每个元素的重复次数
# 0重复2次，1重复3次，2重复4次，3重复5次
np.repeat(arr, [2, 3, 4, 5])

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3])

多维数组repeat

In [25]:
ndarr = np.arange(6).reshape(2, 3)
ndarr

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
np.repeat(ndarr, 2) # 不指定轴会被扁平化

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [30]:
np.repeat(ndarr, 2, axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

In [31]:
np.repeat(ndarr, 2, axis=1)

array([[0, 0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5, 5]])

#### 5.2 tile ———— 针对整个数组

In [35]:
ndarr

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
np.tile(ndarr, 2) # 对标量是横向扩展

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [37]:
np.tile(ndarr, (1,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [39]:
np.tile(ndarr, (2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

### **6、数组转置和轴对换**

- 转置和轴对换返回的是原对象的视图，不是新对象

In [44]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
arr.T[:2] = 0
arr

array([[ 0,  0,  2,  3],
       [ 0,  0,  6,  7],
       [ 0,  0, 10, 11]])