**排序**
- sort(a[, axis, kind, order]) 
> 返回数组的排序副本

- ndarray.sort([axis, kind, order]) 
> 就地对数组进行排序

- lexsort(keys[, axis]) 
> 使用一系列键执行间接排序

- argsort(a[, axis, kind, order]) 
> 返回对数组进行排序的索引

- msort(a) 
> 返回沿第一个轴排序的数组副本

- sort_complex(a) 
> 首先使用实部对复杂数组进行排序，然后使用虚部进行排序

- partition(a, kth[, axis, kind, order]) 
> 返回数组的分区副本

- argpartition(a, kth[, axis, kind, order]) 
> 使用kind关键字指定的算法沿给定轴执行间接分区

In [1]:
import numpy as np

arr1 = np.random.randn(10)
arr1

array([-0.48222165, -2.30739386,  1.95941485,  1.08119545, -0.69638443,
        0.04028632,  0.75619607,  0.5155348 , -0.5422673 , -1.75394304])

In [2]:
np.sort(arr1)

array([-2.30739386, -1.75394304, -0.69638443, -0.5422673 , -0.48222165,
        0.04028632,  0.5155348 ,  0.75619607,  1.08119545,  1.95941485])

In [3]:
arr1.sort() # 就地进行排序，修改原数组
arr1

array([-2.30739386, -1.75394304, -0.69638443, -0.5422673 , -0.48222165,
        0.04028632,  0.5155348 ,  0.75619607,  1.08119545,  1.95941485])

多维数组排序

In [4]:
arr2 = np.random.randn(3, 4)
arr2

array([[-1.77090915, -1.15811429,  0.13914458,  1.59447232],
       [-0.31931722, -0.35300998, -0.07051389, -0.46588781],
       [ 0.07961398, -2.07008481,  0.53152986, -1.18861229]])

In [5]:
np.sort(arr2, axis=1) # 按列排序

array([[-1.77090915, -1.15811429,  0.13914458,  1.59447232],
       [-0.46588781, -0.35300998, -0.31931722, -0.07051389],
       [-2.07008481, -1.18861229,  0.07961398,  0.53152986]])

In [6]:
np.sort(arr2, axis=0) # 按行排序

array([[-1.77090915, -2.07008481, -0.07051389, -1.18861229],
       [-0.31931722, -1.15811429,  0.13914458, -0.46588781],
       [ 0.07961398, -0.35300998,  0.53152986,  1.59447232]])

In [7]:
my_dt = np.dtype([('name',  'U10'),('age',  int)]) # 按关键字排序
my_dt

dtype([('name', '<U10'), ('age', '<i8')])

按键排序

In [8]:
arr3 = np.array([("罗志祥", 21), ("黄渤", 25), ("孙红雷",  17),  ("黄磊",27)], dtype=my_dt)
arr3

array([('罗志祥', 21), ('黄渤', 25), ('孙红雷', 17), ('黄磊', 27)],
      dtype=[('name', '<U10'), ('age', '<i8')])

In [9]:
np.sort(arr3, order='age')

array([('孙红雷', 17), ('罗志祥', 21), ('黄渤', 25), ('黄磊', 27)],
      dtype=[('name', '<U10'), ('age', '<i8')])