**伪随机数生成**

numpy.random模块对Python内置的random进行了补充，增加了一些用于高效生成多种概率分布的样本值的函数
 
之所以被称作**伪随机数**而不是**随机数**是因为它们都是通过算法基于随机数生成器种子在确定性的条件下生成的
 
常用函数：
- rand
> 产生指定形状的均匀分布的样本值

- randint
> 从给定的上下限范围内选取随机整数

- randn
> 产生正态分布（平均值为0，标准差为1）的样本值，类似于MATLAB接口

- binomial
> 产生二项分布的样本值

- normal
> 产生正态（高斯）分布的样本值

- beta
> 产生Beta分布的样本值

- chisquare
> 产生卡方分布的样本值

- gamma
> 产生Gamma分布的样本值

- uniform
> 产生在指定范围中均匀分布的样本值

- seed
> 确定随机数生成器的种子

- permutation
> 返回一个序列的随机排列或返回一个随机排列的范围

- shuffle
> 对一个序列就地随机排列

In [1]:
import numpy as np

In [2]:
np.random.rand(3,4)

array([[0.90161701, 0.31140024, 0.94477967, 0.89587644],
       [0.48772656, 0.91669998, 0.66277684, 0.86206637],
       [0.62573032, 0.59582059, 0.84338165, 0.65502255]])

In [3]:
np.random.randint(5, size=(3, 4))

array([[1, 1, 3, 4],
       [3, 1, 3, 4],
       [2, 2, 2, 0]])

In [4]:
np.random.randn(2, 4)

array([[ 0.60060783, -1.41469429, -1.00260539,  0.54008402],
       [ 1.56796868, -0.16615201,  1.26759971, -1.46960696]])

In [5]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([-0.06421021,  0.05197696, -0.07980718, -0.17480652, -0.10595657,
       -0.17025312, -0.08860704, -0.01037431,  0.01314048, -0.27894384])

In [6]:
# 生成指定范围的样本值
np.random.uniform(1, 2, 100)

array([1.19082727, 1.52692335, 1.84519077, 1.37392774, 1.82982847,
       1.08834768, 1.32187614, 1.84705551, 1.34911109, 1.91915475,
       1.14791553, 1.80312255, 1.58279169, 1.39602613, 1.63546804,
       1.8145144 , 1.71336598, 1.59142333, 1.90996402, 1.77187248,
       1.42441151, 1.80288167, 1.59685399, 1.70113392, 1.81279878,
       1.36353244, 1.24269948, 1.02321881, 1.67569378, 1.0090097 ,
       1.78908056, 1.67380533, 1.80147754, 1.04104863, 1.14681729,
       1.13285637, 1.54284409, 1.02100831, 1.56045196, 1.25009438,
       1.67295887, 1.65639899, 1.89804547, 1.98232023, 1.49735444,
       1.23333709, 1.20581485, 1.46202436, 1.34681572, 1.00603235,
       1.33725157, 1.18318967, 1.80907332, 1.00037452, 1.79822813,
       1.66987181, 1.21015396, 1.42442435, 1.10729257, 1.40595881,
       1.43844938, 1.84924653, 1.25305003, 1.37339943, 1.33049931,
       1.92458695, 1.24492303, 1.17902775, 1.46938506, 1.44292667,
       1.37037554, 1.25467049, 1.32015373, 1.91297675, 1.43155