### **广播**
> 广播是指不同形状的数组之间的算术运算的执行方式。受限于某些约束，较小的数组依据较大数组“broadcasting”，使得它们具有兼容的形状。

**广播的原则**
> 如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符或其中一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。

In [6]:
import numpy as np

arr1 = np.arange(24).reshape(3,4,2)
arr2 = np.array([0,1])

In [7]:
arr1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [8]:
arr2

array([0, 1])

In [9]:
arr1 - arr2

array([[[ 0,  0],
        [ 2,  2],
        [ 4,  4],
        [ 6,  6]],

       [[ 8,  8],
        [10, 10],
        [12, 12],
        [14, 14]],

       [[16, 16],
        [18, 18],
        [20, 20],
        [22, 22]]])