### **广播**
> 广播是指不同形状的数组之间的算术运算的执行方式。受限于某些约束，较小的数组依据较大数组“broadcasting”，使得它们具有兼容的形状。

**广播的原则**
> 如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符或其中一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。

In [1]:
import numpy as np

arr1 = np.arange(24).reshape(3,4,2)
arr2 = np.array([[4],
                [4],
                [4],
                [4]])

In [5]:
arr1, arr1.shape

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]), (3, 4, 2))

In [6]:
arr2, arr2.shape

(array([[4],
        [4],
        [4],
        [4]]), (4, 1))

In [4]:
arr1 - arr2

array([[[-4, -3],
        [-2, -1],
        [ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [11]:
arr3 = np.arange(48).reshape((8, 1, 6, 1))
arr4 = np.arange(35).reshape((7, 1, 5))

In [12]:
arr3 - arr4

array([[[[  0,  -1,  -2,  -3,  -4],
         [  1,   0,  -1,  -2,  -3],
         [  2,   1,   0,  -1,  -2],
         [  3,   2,   1,   0,  -1],
         [  4,   3,   2,   1,   0],
         [  5,   4,   3,   2,   1]],

        [[ -5,  -6,  -7,  -8,  -9],
         [ -4,  -5,  -6,  -7,  -8],
         [ -3,  -4,  -5,  -6,  -7],
         [ -2,  -3,  -4,  -5,  -6],
         [ -1,  -2,  -3,  -4,  -5],
         [  0,  -1,  -2,  -3,  -4]],

        [[-10, -11, -12, -13, -14],
         [ -9, -10, -11, -12, -13],
         [ -8,  -9, -10, -11, -12],
         [ -7,  -8,  -9, -10, -11],
         [ -6,  -7,  -8,  -9, -10],
         [ -5,  -6,  -7,  -8,  -9]],

        ...,

        [[-20, -21, -22, -23, -24],
         [-19, -20, -21, -22, -23],
         [-18, -19, -20, -21, -22],
         [-17, -18, -19, -20, -21],
         [-16, -17, -18, -19, -20],
         [-15, -16, -17, -18, -19]],

        [[-25, -26, -27, -28, -29],
         [-24, -25, -26, -27, -28],
         [-23, -24, -25, -26, -27],
      

(1,)