**二进制文件**
- load(file[, mmap_mode, allow_pickle, …])
> 从.npy，.npz或pickle文件加载数组或pickle对象

- save(file, arr[, allow_pickle, fix_imports])
> 将数组保存为NumPy .npy格式的二进制文件

- savez(file, *args, **kwds)
> 将多个数组以未压缩的.npz格式保存到单个文件中

- savez_compressed(file, *args, **kwds)
> 将多个数组以压缩的.npz格式保存到单个文件中


**文本文件**

- loadtxt(fname[, dtype, comments, delimiter, …])
> 从文本文件加载数据

- savetxt(fname, X[, fmt, delimiter, newline, …])
> 从文本文件加载数据

- genfromtxt(fname[, dtype, comments, …])
> 从文本文件加载数据，并按指定处理缺失值

- fromregex(file, regexp, dtype[, encoding])
> 使用来自文本文件构造数组



In [1]:
import numpy as np
from io import BytesIO

arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
np.save('file/io', arr)

In [3]:
np.load('file/io.npy')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.savetxt('file/io2', arr)

In [5]:
np.savetxt('file/io2', arr, delimiter=',')

In [6]:
np.loadtxt('file/io2', delimiter=',')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])