**条件逻辑**

In [10]:
import numpy as np

# np.where()
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array(['a', 'b', 'c', 'd', 'e'])
cond = np.array([True, False, True, False, True])

In [11]:
result = np.where(cond, arr1, arr2)
result

array(['1', 'b', '3', 'd', '5'], dtype='<U11')

In [12]:
# 将arr1中大于3的全部变为-3
np.where(arr1 > 3, -3, arr1)

array([ 1,  2,  3, -3, -3])

In [13]:
# 将arr1中大于3的全部变为该值的相反数
np.where(arr1 > 3, -arr1, arr1)

array([ 1,  2,  3, -4, -5])

**数学和统计方法**
<table border="1" style="text-align:left;">
    <tr><th>函数</th><th>说明</th></tr>
    <tr><td>sum</td><td>对数组中全部或某轴向的元素求和</td></tr>
    <tr><td>mean</td><td>算术平均数。零长度数组的mean为NaN</td></tr>
    <tr><td>std、var</td><td>分别为标准差和方差，自由度可调（默认为n）</td></tr>
    <tr><td>min、max</td><td>最大值和最小值</td></tr>
    <tr><td>argmin、argmax</td><td>分别为最大和最小元素的索引</td></tr>
    <tr><td>cumsum</td><td>所有元素的累计和</td></tr>
    <tr><td>cumprod</td><td>所有元素的累计积</td></tr>
</table>

In [15]:
arr3 = np.arange(12).reshape(3, 4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
arr3.sum() # 等效于np.sum(arr3)

66

In [24]:
arr.sum(axis=1) # 计算每一行的和

array([ 6, 22, 38])

In [20]:
arr3.mean() # 等效于np.mean(arr3)

66

In [23]:
arr3.mean(axis=0) # 计算每一列的平均值

array([4., 5., 6., 7.])

In [31]:
import docx
from docx import Document



ImportError: DLL load failed: 找不到指定的程序。