**排序**
- sort()
    - arr.sort()会直接修改arr本身
    - np.sort()返回一个排序后的副本，不修改原数组

    参数说明:
    > sort(axis=-1, kind='quicksort', order=None)
    > 
    > axis：排序沿数组的（轴）方向，0表示按行，1表示按列，None表示展开来排序，默认值为-1，表示沿最后的轴排序
    >
    > kind：排序的算法，提供了快排'quicksort'、混排'mergesort'、堆排'heapsort'， 默认为‘quicksort'
    >
    > order：排序的字段名，可指定字段排序，默认为None

- lexsort(keys[, axis])	使用一系列键执行间接排序。
- argsort(a[, axis, kind, order])	返回对数组进行排序的索引。
- ndarray.sort([axis, kind, order])	就地对数组进行排序。
- msort(a)	返回沿第一个轴排序的数组副本。
- sort_complex(a)	首先使用实部对复杂数组进行排序，然后使用虚部进行排序。
- partition(a, kth[, axis, kind, order])	返回数组的分区副本。
- argpartition(a, kth[, axis, kind, order])	使用kind关键字指定的算法沿给定轴执行间接分区。


In [3]:
import numpy as np

arr1 = np.random.randn(10)
arr1

array([ 1.88127464,  0.0743766 ,  0.2329814 ,  0.73940387, -0.14720025,
       -0.1894937 ,  1.54240596,  2.03836122, -0.5496149 ,  1.26693548])

In [5]:
np.sort(arr1)

array([-0.5496149 , -0.1894937 , -0.14720025,  0.0743766 ,  0.2329814 ,
        0.73940387,  1.26693548,  1.54240596,  1.88127464,  2.03836122])

In [6]:
arr1.sort()
arr1

array([-0.5496149 , -0.1894937 , -0.14720025,  0.0743766 ,  0.2329814 ,
        0.73940387,  1.26693548,  1.54240596,  1.88127464,  2.03836122])

多维数组排序

In [7]:
arr2 = np.random.randn(3, 4)
arr2

array([[-1.75004932,  0.171558  , -1.46631359,  0.23185265],
       [-0.79028465, -0.54076154, -1.44156697,  0.10869921],
       [-0.16732002, -1.46377183, -0.28347901, -1.2208518 ]])

In [8]:
np.sort(arr2, axis=1) # 按列排序，列不变行变

array([[-1.75004932, -1.46631359,  0.171558  ,  0.23185265],
       [-1.44156697, -0.79028465, -0.54076154,  0.10869921],
       [-1.46377183, -1.2208518 , -0.28347901, -0.16732002]])

In [9]:
np.sort(arr2, axis=0) # 按行排序，行不变列变

array([[-1.75004932, -1.46377183, -1.46631359, -1.2208518 ],
       [-0.79028465, -0.54076154, -1.44156697,  0.10869921],
       [-0.16732002,  0.171558  , -0.28347901,  0.23185265]])

In [10]:
my_dt = np.dtype([('name',  'S10'),('age',  int)])
my_dt

dtype([('name', 'S10'), ('age', '<i8')])

In [11]:
arr3 = np.array([("Mike",21),("Nancy",25),("Bob",  17),  ("Jane",27)], dtype=my_dt)
arr3

array([(b'Mike', 21), (b'Nancy', 25), (b'Bob', 17), (b'Jane', 27)],
      dtype=[('name', 'S10'), ('age', '<i8')])

In [13]:
np.sort(arr3, order='age')

array([(b'Bob', 17), (b'Mike', 21), (b'Nancy', 25), (b'Jane', 27)],
      dtype=[('name', 'S10'), ('age', '<i8')])